version: '2'
services:
  permanent-302:
    build: ./flask
    restart: always

  nginx:
    image: nginx
    depends_on:
      - permanent-302
    ports:
      - "127.0.0.1:30006:80"
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
