version: '2'
services:
  make-some-noise:
    build: ./flask
    restart: always

  nginx:
    image: nginx
    depends_on:
      - make-some-noise
    ports:
      - "127.0.0.1:30009:80"
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
